### ISSUE TITLE
Include examples of serif and mono 

### ISSUE THREAD

**Issue by Josh-a-e** [tmcw/systemfontstack#23] opened 2022-05-29 10:31 UTC

**Comment by tmcw** [comment] 2022-05-29 12:09
Guessing this means "screenshots" based on the terse title. Duplicate of #2. It'd be very cool to do a preview of what the font stacks look like on different computers. I'd accept the PR, but I don't have the time to implement that myself right now.

**Closed as completed by tmcw** 2022-05-29 12:09 UTC
